"""Simulation utilities for insertion-deletion-substitution DNA channels."""

from __future__ import annotations

import math
import random
from numbers import Real

DNA_ALPHABET = "ACGT"


def _validate_probability(name: str, value: float) -> None:
    """Validate one finite probability in the closed interval [0, 1]."""
    if isinstance(value, bool) or not isinstance(value, Real):
        raise TypeError(f"{name} must be a real number")
    if not math.isfinite(value) or not 0.0 <= value <= 1.0:
        raise ValueError(f"{name} must be between 0 and 1")


def _validate_channel_parameters(
    sequence: str,
    insertion_probability: float,
    deletion_probability: float,
    substitution_probability: float,
) -> None:
    """Validate the sequence and the categorical channel probabilities."""
    if not isinstance(sequence, str):
        raise TypeError("sequence must be a string")

    invalid_bases = sorted(set(sequence) - set(DNA_ALPHABET))
    if invalid_bases:
        raise ValueError(f"Invalid DNA bases: {invalid_bases}")

    probabilities = {
        "insertion_probability": insertion_probability,
        "deletion_probability": deletion_probability,
        "substitution_probability": substitution_probability,
    }
    for name, probability in probabilities.items():
        _validate_probability(name, probability)

    total_error_probability = sum(probabilities.values())
    if total_error_probability > 1.0:
        raise ValueError("The sum of IDS probabilities cannot exceed 1")

    if insertion_probability == 1.0:
        raise ValueError("insertion_probability must be less than 1 so the channel terminates")


def simulate_ids_channel(
    sequence: str,
    insertion_probability: float,
    deletion_probability: float,
    substitution_probability: float,
    rng: random.Random,
) -> str:
    """Return one noisy trace generated by a categorical IDS channel.

    At each channel event exactly one action is sampled: insertion, deletion,
    substitution, or unchanged transmission. An insertion emits a random DNA
    base without advancing the input pointer. This permits multiple consecutive
    insertions before the same source base. Deletions, substitutions, and
    unchanged transmissions advance the input pointer by one position.

    The remaining probability after the three error probabilities is the
    probability of transmitting the current base unchanged. The function does
    not generate insertions after the final source base has been consumed.

    Args:
        sequence: Source DNA sequence containing only A, C, G, and T.
        insertion_probability: Probability of an insertion event.
        deletion_probability: Probability of deleting the current source base.
        substitution_probability: Probability of replacing the current base.
        rng: Explicit random generator used for reproducible simulation.

    Returns:
        A potentially shorter or longer noisy DNA trace.

    Raises:
        TypeError: If the sequence or probabilities have invalid types.
        ValueError: If bases or probability values are invalid.
    """
    _validate_channel_parameters(
        sequence=sequence,
        insertion_probability=insertion_probability,
        deletion_probability=deletion_probability,
        substitution_probability=substitution_probability,
    )

    if not hasattr(rng, "random") or not hasattr(rng, "choice"):
        raise TypeError("rng must provide random() and choice() methods")

    insertion_threshold = insertion_probability
    deletion_threshold = insertion_threshold + deletion_probability
    substitution_threshold = deletion_threshold + substitution_probability

    output: list[str] = []
    source_index = 0

    while source_index < len(sequence):
        event = rng.random()

        if event < insertion_threshold:
            output.append(rng.choice(DNA_ALPHABET))
            continue

        source_base = sequence[source_index]

        if event < deletion_threshold:
            source_index += 1
            continue

        if event < substitution_threshold:
            alternatives = DNA_ALPHABET.replace(source_base, "")
            output.append(rng.choice(alternatives))
            source_index += 1
            continue

        output.append(source_base)
        source_index += 1

    return "".join(output)


def generate_trace_cluster(
    sequence: str,
    cluster_size: int,
    insertion_probability: float,
    deletion_probability: float,
    substitution_probability: float,
    rng: random.Random,
) -> list[str]:
    """Generate independent noisy traces from one source sequence."""
    if isinstance(cluster_size, bool) or not isinstance(cluster_size, int):
        raise TypeError("cluster_size must be an integer")
    if cluster_size < 1:
        raise ValueError("cluster_size must be at least 1")

    return [
        simulate_ids_channel(
            sequence=sequence,
            insertion_probability=insertion_probability,
            deletion_probability=deletion_probability,
            substitution_probability=substitution_probability,
            rng=rng,
        )
        for _ in range(cluster_size)
    ]
