"""A small supervised reranker for HelixTrace reconstruction candidates.

The model is deliberately simple and inspectable: ridge regression predicts a
normalized-edit-distance-like score from features that are available at
inference time.  It then selects one of the four existing deterministic
reconstruction candidates.  The source strand is used only by the offline
training script to create regression targets; it is never an inference input.

The committed weights were fitted on controlled synthetic data.  This module
does not claim that those data represent a wet-lab sequencing distribution.
"""

from __future__ import annotations

import math
import statistics
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from numbers import Real

from dna_trace_reconstruction.constraints import evidence_cost, summarize_biological_constraints
from dna_trace_reconstruction.ids_channel import DNA_ALPHABET
from dna_trace_reconstruction.metrics import levenshtein_distance, normalized_edit_distance

METHOD_NAMES = ("medoid", "consensus", "unconstrained", "constrained")

FEATURE_NAMES = (
    "normalized_evidence_cost",
    "normalized_evidence_cost_above_best",
    "signed_length_gap_from_median_trace",
    "absolute_length_gap_from_median_trace",
    "distance_from_consensus",
    "distance_from_medoid",
    "normalized_gc_excess",
    "normalized_homopolymer_excess",
    "biologically_valid",
    "candidate_agreement_fraction",
    "method_is_medoid",
    "method_is_consensus",
    "method_is_unconstrained",
    "method_is_constrained",
    "mean_pairwise_trace_distance",
    "trace_length_spread",
    "medoid_x_trace_distance",
    "consensus_x_trace_distance",
    "unconstrained_x_trace_distance",
    "constrained_x_trace_distance",
    "medoid_x_inverse_cluster_size",
    "consensus_x_inverse_cluster_size",
    "unconstrained_x_inverse_cluster_size",
    "constrained_x_inverse_cluster_size",
)


@dataclass(frozen=True, slots=True)
class LinearRerankerModel:
    """Versioned parameters for a standardized linear ridge model."""

    version: str
    feature_names: tuple[str, ...]
    feature_means: tuple[float, ...]
    feature_scales: tuple[float, ...]
    intercept: float
    weights: tuple[float, ...]
    training_seed: int
    training_experiments: int
    ridge_alpha: float

    def __post_init__(self) -> None:
        feature_count = len(self.feature_names)
        if not (
            len(self.feature_means) == feature_count
            and len(self.feature_scales) == feature_count
            and len(self.weights) == feature_count
        ):
            raise ValueError("model feature arrays must have equal lengths")
        if any(scale <= 0.0 or not math.isfinite(scale) for scale in self.feature_scales):
            raise ValueError("model feature scales must be finite and positive")

    def predict(self, features: Sequence[float]) -> float:
        """Return the model's unbounded predicted error score (lower is better)."""
        if isinstance(features, str | bytes) or len(features) != len(self.feature_names):
            raise ValueError(f"features must contain {len(self.feature_names)} numeric values")

        score = self.intercept
        for value, mean, scale, weight in zip(
            features,
            self.feature_means,
            self.feature_scales,
            self.weights,
            strict=True,
        ):
            if isinstance(value, bool) or not isinstance(value, Real):
                raise TypeError("model features must be numeric")
            if not math.isfinite(value):
                raise ValueError("model features must be finite")
            score += weight * ((value - mean) / scale)
        return score


@dataclass(frozen=True, slots=True)
class CandidateScore:
    """One candidate and the observable evidence used to score it."""

    name: str
    sequence: str
    predicted_error_score: float
    evidence_cost: float
    features: tuple[float, ...]


@dataclass(frozen=True, slots=True)
class RerankerResult:
    """Deterministic output of learned candidate selection."""

    selected_name: str
    selected_sequence: str
    model_version: str
    scores: tuple[CandidateScore, ...]


# Generated by scripts/train_reranker.py with 80 training experiments,
# master seed 20260720, ridge alpha 10.0, and the distribution documented in
# that script.  Keeping the small parameter vector in source makes inference
# dependency-free and makes every weight reviewable in version control.
DEFAULT_MODEL = LinearRerankerModel(
    version="helixtrace-linear-reranker-v1",
    feature_names=FEATURE_NAMES,
    feature_means=(
        0.14554757909699573,
        0.0075664352033359234,
        -0.005380170653197855,
        0.017318009687415176,
        0.01771623432656941,
        0.04356419208914082,
        0.0017487125541239725,
        0.0009993156115758902,
        0.840625,
        0.540625,
        0.25,
        0.25,
        0.25,
        0.25,
        0.23353361416924345,
        0.10125016692319273,
        0.05838340354231082,
        0.05838340354231082,
        0.05838340354231082,
        0.05838340354231082,
        0.04864583333333332,
        0.04864583333333332,
        0.04864583333333332,
        0.04864583333333332,
    ),
    feature_scales=(
        0.05401482198947071,
        0.013864799771377985,
        0.024242944323220047,
        0.017797559556941286,
        0.026714692298829282,
        0.03769736198740771,
        0.0066645253014073124,
        0.00379451659426608,
        0.36602542176056585,
        0.2513828939585984,
        0.4330127018922193,
        0.4330127018922193,
        0.4330127018922193,
        0.4330127018922193,
        0.07437049390741936,
        0.04602871004253017,
        0.10774325045477953,
        0.10774325045477953,
        0.10774325045477952,
        0.10774325045477953,
        0.09492661933322864,
        0.09492661933322864,
        0.09492661933322864,
        0.09492661933322866,
    ),
    intercept=0.04712716640583685,
    weights=(
        0.023820715686418633,
        0.00381823003588726,
        -0.0030396611671210526,
        -0.0006726701926710285,
        0.004389380851985674,
        -0.010602275450479287,
        0.0011394708327528954,
        0.0008090012368445775,
        -0.00022730381458698474,
        -0.003066026040620915,
        -0.002770893416295461,
        -2.756342264970647e-05,
        0.0015282600783302531,
        0.001270196760622562,
        0.005534790564652847,
        -0.005222757807731284,
        0.005749746221843383,
        0.00021285941832288003,
        -0.001024060523388942,
        -0.0011181191854153251,
        0.018636626380142476,
        0.019312084254708296,
        0.018015304813469527,
        0.018471349408684758,
    ),
    training_seed=20260720,
    training_experiments=80,
    ridge_alpha=10.0,
)


def _validate_dna(name: str, sequence: str) -> None:
    if not isinstance(sequence, str):
        raise TypeError(f"{name} must be a string")
    invalid_bases = sorted(set(sequence) - set(DNA_ALPHABET))
    if invalid_bases:
        raise ValueError(f"{name} contains invalid DNA bases: {invalid_bases}")


def _validate_inputs(
    traces: Sequence[str], candidates: Mapping[str, str]
) -> tuple[tuple[str, ...], dict[str, str]]:
    if isinstance(traces, str | bytes) or not isinstance(traces, Sequence):
        raise TypeError("traces must be a sequence of DNA strings")
    if not traces:
        raise ValueError("traces must contain at least one DNA trace")
    normalized_traces = tuple(traces)
    for index, trace in enumerate(normalized_traces):
        _validate_dna(f"traces[{index}]", trace)

    if not isinstance(candidates, Mapping):
        raise TypeError("candidates must be a mapping")
    expected_names = set(METHOD_NAMES)
    observed_names = set(candidates)
    if observed_names != expected_names:
        missing = sorted(expected_names - observed_names)
        extra = sorted(observed_names - expected_names)
        raise ValueError(
            f"candidates require exactly {METHOD_NAMES}; missing={missing}, extra={extra}"
        )

    normalized_candidates = {name: candidates[name] for name in METHOD_NAMES}
    for name, sequence in normalized_candidates.items():
        _validate_dna(f"candidates[{name!r}]", sequence)
    return normalized_traces, normalized_candidates


def _mean_pairwise_trace_distance(traces: tuple[str, ...]) -> float:
    distances = [
        normalized_edit_distance(first, second)
        for first_index, first in enumerate(traces)
        for second in traces[first_index + 1 :]
    ]
    return statistics.fmean(distances) if distances else 0.0


def extract_candidate_features(
    traces: Sequence[str], candidates: Mapping[str, str]
) -> dict[str, tuple[float, ...]]:
    """Return source-free feature vectors for the four named candidates."""
    normalized_traces, normalized_candidates = _validate_inputs(traces, candidates)
    trace_length_median = statistics.median(len(trace) for trace in normalized_traces)
    scale = max(1.0, trace_length_median)
    pairwise_distance = _mean_pairwise_trace_distance(normalized_traces)
    trace_length_spread = (
        max(map(len, normalized_traces)) - min(map(len, normalized_traces))
    ) / scale
    inverse_cluster_size = 1.0 / len(normalized_traces)

    evidence_costs = {
        name: evidence_cost(sequence, normalized_traces)
        for name, sequence in normalized_candidates.items()
    }
    minimum_evidence_cost = min(evidence_costs.values())
    consensus = normalized_candidates["consensus"]
    medoid = normalized_candidates["medoid"]

    feature_vectors: dict[str, tuple[float, ...]] = {}
    for name in METHOD_NAMES:
        sequence = normalized_candidates[name]
        summary = summarize_biological_constraints(sequence)
        method_indicators = tuple(float(name == method) for method in METHOD_NAMES)
        agreement_fraction = sum(
            candidate == sequence for candidate in normalized_candidates.values()
        ) / len(METHOD_NAMES)
        sequence_length = max(1, len(sequence))

        feature_vectors[name] = (
            evidence_costs[name] / scale,
            (evidence_costs[name] - minimum_evidence_cost) / scale,
            (len(sequence) - trace_length_median) / scale,
            abs(len(sequence) - trace_length_median) / scale,
            levenshtein_distance(sequence, consensus) / max(1, len(consensus)),
            levenshtein_distance(sequence, medoid) / max(1, len(medoid)),
            summary.gc_excess / sequence_length,
            summary.homopolymer_excess / sequence_length,
            float(summary.valid),
            agreement_fraction,
            *method_indicators,
            pairwise_distance,
            trace_length_spread,
            *(indicator * pairwise_distance for indicator in method_indicators),
            *(indicator * inverse_cluster_size for indicator in method_indicators),
        )

    return feature_vectors


def rerank_candidates(
    traces: Sequence[str],
    candidates: Mapping[str, str],
    *,
    model: LinearRerankerModel = DEFAULT_MODEL,
) -> RerankerResult:
    """Select one deterministic reconstruction using the learned linear score.

    Candidate generation remains the responsibility of the existing pipeline.
    The four required names deliberately match its medoid, alignment consensus,
    evidence-only refinement, and biology-aware refinement outputs.
    """
    normalized_traces, normalized_candidates = _validate_inputs(traces, candidates)
    if model.feature_names != FEATURE_NAMES:
        raise ValueError("model feature names do not match this feature extractor")

    feature_vectors = extract_candidate_features(normalized_traces, normalized_candidates)
    scores = tuple(
        CandidateScore(
            name=name,
            sequence=normalized_candidates[name],
            predicted_error_score=model.predict(feature_vectors[name]),
            evidence_cost=evidence_cost(normalized_candidates[name], normalized_traces),
            features=feature_vectors[name],
        )
        for name in METHOD_NAMES
    )
    selected = min(
        scores, key=lambda score: (score.predicted_error_score, METHOD_NAMES.index(score.name))
    )
    return RerankerResult(
        selected_name=selected.name,
        selected_sequence=selected.sequence,
        model_version=model.version,
        scores=scores,
    )
